### ISSUE TITLE
сделать возможность 'Обновление задачи'

### ISSUE THREAD

**Issue by Mihailmihail111** [Mihailmihail111/planfix#3]

**Comment by Mihailmihail111** [comment]
обновления информации задачи можно посмотреть как это реализовано в planfix

**Comment by githubeing** [comment]
даты и статуса пока нету. есть только операция обновления. поля те же что и для остальных операций: название, описание, id, general : [https://github.com/Mihailmihail111/planfix/commit/ea3d59d2939b28fe4c387db06781f92ff8a42791](url)

**Comment by githubeing** [comment]
сделаю просмотр, а потом добавлю поля - там много доменной логики пилить

**Comment by githubeing** [comment]
дату пока добавил только в доменный класс задачи
@Mihailmihail111 , зацени. устно расскажу

**Comment by githubeing** [comment]
не думал, что с датами окажется всё так сложно
